<script module lang="ts">
  import { defineMeta } from '@storybook/addon-svelte-csf';
  import RecoveryPhrase from './RecoveryPhrase.svelte';

  // 24-word BIP39-style phrase. Real production output is generated by the
  // Rust backend; this fixture keeps Storybook deterministic.
  const phrase =
    'alpha bravo charlie delta echo foxtrot golf hotel india juliet ' +
    'kilo lima mike november oscar papa quebec romeo sierra tango ' +
    'uniform victor whiskey xray';

  const { Story } = defineMeta({
    title: 'Components/RecoveryPhrase',
    component: RecoveryPhrase,
    tags: ['autodocs'],
    parameters: {
      layout: 'fullscreen',
    },
    args: {
      phrase,
      onAcknowledged: (): void => {},
    },
  });
</script>

<Story name="Default" args={{ phrase }} />
<Story name="ShortPhrase" args={{ phrase: 'one two three four' }} />
